import { ResponseScript } from "../../types/index.js";

// ── 2. Report summary — context + one tool call ───────────
export const reportSummaryScript = {
  id: "report_summary",
  name: "Report Summary",
  triggers: [
    "report",
    "summary",
    "summarize",
    "quarterly",
    "q3",
    "q4",
    "earnings",
  ],
  events: [
    {
      kind: "context",
      context_id: "ctx_report",
      data: {
        report: "Q3-2025-Financial",
        pages: 47,
        sections: ["revenue", "operations", "forecast", "risks"],
        last_updated: "2025-10-15T09:30:00Z",
        source: "internal-docs/finance/quarterly",
        access_level: "confidential",
      },
    },
    { kind: "token", text: "Based on " },
    { kind: "token", text: "the Q3 financial " },
    { kind: "token", text: "report, the overall " },
    { kind: "token", text: "performance shows " },
    { kind: "token", text: "strong growth " },
    { kind: "token", text: "across key metrics. " },
    { kind: "token", text: "Revenue grew " },
    {
      kind: "tool_call",
      tool_name: "lookup_metric",
      args: { metric: "revenue_yoy", quarter: "Q3-2025" },
      result: {
        value: "23.4%",
        period: "YoY",
        raw_amount: 4250000,
        currency: "USD",
      },
    },
    { kind: "token", text: "23.4% year-over-year, " },
    { kind: "token", text: "reaching $4.25M " },
    { kind: "token", text: "for the quarter. " },
    { kind: "token", text: "This growth was " },
    { kind: "token", text: "primarily driven by " },
    { kind: "token", text: "enterprise client " },
    { kind: "token", text: "expansion, with the " },
    { kind: "token", text: "top 10 accounts " },
    { kind: "token", text: "contributing 68% " },
    { kind: "token", text: "of new ARR. " },
    {
      kind: "context",
      context_id: "ctx_report",
      data: {
        report: "Q3-2025-Financial",
        pages: 47,
        sections: ["revenue", "operations", "forecast", "risks"],
        last_updated: "2025-10-15T09:30:00Z",
        source: "internal-docs/finance/quarterly",
        access_level: "confidential",
        current_focus: "operations",
        extracted_metrics: {
          revenue_yoy: "23.4%",
          operating_margin: "34%",
          prev_operating_margin: "28%",
        },
      },
    },
    { kind: "token", text: "Operating margins " },
    { kind: "token", text: "improved to 34%, " },
    { kind: "token", text: "up from 28% in Q2, " },
    { kind: "token", text: "largely due to " },
    { kind: "token", text: "infrastructure cost " },
    { kind: "token", text: "optimization and " },
    { kind: "token", text: "the migration to " },
    { kind: "token", text: "spot instances for " },
    { kind: "token", text: "non-critical workloads. " },
    { kind: "token", text: "The forecast section " },
    { kind: "token", text: "indicates continued " },
    { kind: "token", text: "momentum, with Q4 " },
    { kind: "token", text: "projections suggesting " },
    { kind: "token", text: "a potential 15-18% " },
    { kind: "token", text: "sequential increase." },
  ],
} satisfies ResponseScript;
