import { ResponseScript } from "../../types/index.js";

// ── 3. Multi-tool analysis — two tool calls ───────────────
export const multiToolScript = {
  id: "multi_tool",
  name: "Multi-Tool Analysis",
  triggers: ["analyze", "compare", "correlation", "analysis", "relationship"],
  events: [
    {
      kind: "context",
      context_id: "ctx_analysis",
      data: {
        analysis_type: "correlation",
        datasets: ["user_growth", "revenue", "churn"],
        timeframe: "2024-01 to 2025-09",
        requested_by: "product-team",
      },
    },
    { kind: "token", text: "Let me analyze " },
    { kind: "token", text: "the relationship " },
    { kind: "token", text: "between your " },
    { kind: "token", text: "key metrics. " },
    {
      kind: "tool_call",
      tool_name: "fetch_dataset",
      args: {
        dataset: "user_growth",
        timeframe: "2024-01:2025-09",
        granularity: "monthly",
      },
      result: {
        total_records: 2847,
        growth_rate: 0.12,
        trend: "accelerating",
        last_month_delta: 347,
      },
    },
    { kind: "token", text: "User growth data " },
    { kind: "token", text: "shows 2,847 new " },
    { kind: "token", text: "accounts over the " },
    { kind: "token", text: "period with a 12% " },
    { kind: "token", text: "compound monthly " },
    { kind: "token", text: "growth rate. The " },
    { kind: "token", text: "trend is accelerating, " },
    { kind: "token", text: "particularly in the " },
    { kind: "token", text: "last quarter. Now " },
    { kind: "token", text: "let me check how " },
    { kind: "token", text: "this correlates " },
    { kind: "token", text: "with revenue. " },
    {
      kind: "tool_call",
      tool_name: "compute_correlation",
      args: { metrics: ["user_growth", "revenue"], method: "pearson" },
      result: {
        correlation: 0.87,
        p_value: 0.001,
        lag_months: 2,
        confidence: "high",
        sample_size: 21,
      },
    },
    { kind: "token", text: "The Pearson " },
    { kind: "token", text: "correlation between " },
    { kind: "token", text: "user growth and " },
    { kind: "token", text: "revenue is 0.87 " },
    { kind: "token", text: "with high confidence " },
    { kind: "token", text: "(p < 0.001), but " },
    { kind: "token", text: "with a notable " },
    { kind: "token", text: "2-month lag. This " },
    { kind: "token", text: "suggests that user " },
    { kind: "token", text: "acquisition translates " },
    { kind: "token", text: "to revenue with " },
    { kind: "token", text: "approximately a " },
    { kind: "token", text: "60-day delay, " },
    { kind: "token", text: "likely reflecting " },
    { kind: "token", text: "your trial-to-paid " },
    { kind: "token", text: "conversion cycle." },
  ],
} satisfies ResponseScript;
