import { ResponseScript } from "../../types.js";

// ── 6. Long response — many tokens + tool call ────────────
export const longResponseScript = {
  id: "long_response",
  name: "Long Detailed Response",
  triggers: [
    "long",
    "detailed",
    "document",
    "write",
    "explain in detail",
    "comprehensive",
  ],
  events: [
    {
      kind: "context",
      context_id: "ctx_doc",
      data: {
        document_type: "technical_brief",
        topic: "context_engine_architecture",
        audience: "engineering_team",
      },
    },
    { kind: "token", text: "The context engine " },
    { kind: "token", text: "architecture is built " },
    { kind: "token", text: "around three core " },
    { kind: "token", text: "principles: verifiable " },
    { kind: "token", text: "retrieval, persistent " },
    { kind: "token", text: "memory, and sub-200ms " },
    { kind: "token", text: "latency at the p99. " },
    { kind: "token", text: "At its foundation, " },
    { kind: "token", text: "the engine maintains " },
    { kind: "token", text: "a directed acyclic " },
    { kind: "token", text: "graph of context " },
    { kind: "token", text: "nodes, where each " },
    { kind: "token", text: "node represents a " },
    { kind: "token", text: "discrete unit of " },
    { kind: "token", text: "business knowledge " },
    { kind: "token", text: "with provenance " },
    { kind: "token", text: "metadata attached. " },
    { kind: "token", text: "When an agent " },
    { kind: "token", text: "requests context, " },
    { kind: "token", text: "the engine performs " },
    { kind: "token", text: "a weighted traversal " },
    { kind: "token", text: "of this graph, " },
    { kind: "token", text: "scoring relevance " },
    { kind: "token", text: "against the current " },
    { kind: "token", text: "query and session " },
    { kind: "token", text: "history. " },
    {
      kind: "tool_call",
      tool_name: "fetch_architecture_diagram",
      args: { component: "context_engine", format: "summary" },
      result: {
        layers: ["ingestion", "indexing", "retrieval", "caching"],
        throughput: "12k_queries_per_second",
        p99_latency_ms: 187,
        storage_backend: "hybrid_vector_kv",
      },
    },
    { kind: "token", text: "The architecture " },
    { kind: "token", text: "consists of four " },
    { kind: "token", text: "layers. The ingestion " },
    { kind: "token", text: "layer handles document " },
    { kind: "token", text: "parsing, chunking, " },
    { kind: "token", text: "and entity extraction. " },
    { kind: "token", text: "The indexing layer " },
    { kind: "token", text: "maintains both vector " },
    { kind: "token", text: "embeddings and " },
    { kind: "token", text: "structured metadata " },
    { kind: "token", text: "indices. The retrieval " },
    { kind: "token", text: "layer performs hybrid " },
    { kind: "token", text: "search combining " },
    { kind: "token", text: "semantic similarity " },
    { kind: "token", text: "with keyword matching " },
    { kind: "token", text: "and graph traversal. " },
    { kind: "token", text: "Finally, the caching " },
    { kind: "token", text: "layer maintains a " },
    { kind: "token", text: "session-scoped LRU " },
    { kind: "token", text: "cache that reduces " },
    { kind: "token", text: "redundant retrievals " },
    { kind: "token", text: "by approximately 40%. " },
    { kind: "token", text: "Current throughput " },
    { kind: "token", text: "sits at 12,000 queries " },
    { kind: "token", text: "per second with a " },
    { kind: "token", text: "p99 latency of 187ms, " },
    { kind: "token", text: "well within the " },
    { kind: "token", text: "sub-200ms target. " },
    { kind: "token", text: "The storage backend " },
    { kind: "token", text: "uses a hybrid " },
    { kind: "token", text: "vector-KV store " },
    { kind: "token", text: "that collocates " },
    { kind: "token", text: "embeddings with " },
    { kind: "token", text: "their source metadata, " },
    { kind: "token", text: "avoiding the join " },
    { kind: "token", text: "penalty that plagues " },
    { kind: "token", text: "separate vector and " },
    { kind: "token", text: "relational stores." },
  ],
} satisfies ResponseScript;
